---

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  location: 'West Europe'
  rgName: 'UiPath-Learn'
  subscription: 'loginsp'
  templateUrl: 'https://raw.githubusercontent.com/Sebastian-Negoescu/UiPath-Learn/master/armtemplates/azdeploy_win.json'
  parametersUrl: 'https://raw.githubusercontent.com/Sebastian-Negoescu/UiPath-Learn/master/armtemplates/azdeploy_win.parameters.json'

# Starting the Resource Creation phase
steps:
- task: AzureResourceGroupDeployment@2
  name: win_deploy
  displayName: "Deploying the Resources for Windows"
  inputs:
    azureSubscription: $(subscription)
    resourceGroupName: $(rgName)
    csmFileLink: $(templateUrl)
    csmParametersFileLink: $(parametersUrl)
    deployMentMode: 'Incremental'
    location: $(location)
    

...