---

trigger:
- master

variables:
  location: 'West Europe'
  rgName: 'UiPath-Learn'
  subscription: 'loginsp'
  templateUrl_win: 'https://raw.githubusercontent.com/Sebastian-Negoescu/UiPath-Learn/master/armtemplates/azdeploy_win.json'
  templateUrl_lin: 'https://raw.githubusercontent.com/Sebastian-Negoescu/UiPath-Learn/master/armtemplates/azdeploy_linux.json'
  parametersUrl_win: 'https://raw.githubusercontent.com/Sebastian-Negoescu/UiPath-Learn/master/armtemplates/azdeploy_win.parameters.json'
  parametersUrl_lin: 'https://raw.githubusercontent.com/Sebastian-Negoescu/UiPath-Learn/master/armtemplates/azdeploy_linux.parameters.json'

# Starting the Resource Creation phase || Testing parallelism with Stages


stages:
- stage: just_a_mimmick
  displayName: "Am I parallel...?"
  jobs:
  - job: parallel_try
    displayName: "Parallel Job try"
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: 'echo "Hello World!"'
      name: "Hello_World"

- stage: windows_stage
  displayName: 'Windows Stage'
  dependsOn: just_a_mimmick
  jobs:
  - job: deployment_windows
    displayName: 'Deployment of Windows'
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: AzureResourceGroupDeployment@2
      name: win_deploy
      displayName: "Deploying the Resources for Windows."
      inputs:
        azureSubscription: $(subscription)
        resourceGroupName: $(rgName)
        action: Create Or Update Resource Group
        templateLocation: URL of the file
        csmFileLink: $(templateUrl_win)
        csmParametersFileLink: $(parametersUrl_win)
        deployMentMode: 'Incremental'
        location: $(location)

- stage: linux_stage
  displayName: 'Linux Stage'
  dependsOn: just_a_mimmick
  jobs:  
  - job: deployment_linux
    displayName: 'Deployment of Linux'
    pool:
      vmAgent: 'Ubuntu-16.04'
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: "Deploying the Resources for Linux."
      inputs:
        azureSubscription: $(subscription)
        resourceGroupName: $(rgName)
        location: $(location)
        action: Create Or Update Resource Group
        templateLocation: URL of the file
        csmFileLink: $(templateUrl_lin)
        csmParametersFileLink: $(parametersUrl_lin)
        deploymentMode: 'Incremental' 


...
