---

trigger:
- master

variables:
  location: 'West Europe'
  rgName: 'UiPath-Learn'
  subscription: 'loginsp'
  templateUrl: 'https://raw.githubusercontent.com/Sebastian-Negoescu/UiPath-Learn/master/armtemplates/azdeploy_win.json'
  parametersUrl: 'https://raw.githubusercontent.com/Sebastian-Negoescu/UiPath-Learn/master/armtemplates/azdeploy_win.parameters.json'

# Starting the Resource Creation phase
jobs:
- job: deployment_windows
  displayName: 'Deployment of Windows'
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - task: AzureResourceGroupDeployment@2
    name: win_deploy
    displayName: "Deploying the Resources for Windows"
    inputs:
      azureSubscription: $(subscription)
      resourceGroupName: $(rgName)
      action: Create Or Update Resource Group
      templateLocation: URL of the file
      csmFileLink: $(templateUrl)
      csmParametersFileLink: $(parametersUrl)
      deployMentMode: 'Incremental'
      location: $(location)    

...